runtime: python39
handlers:
  - url: /
    static_files: index.html
    upload: index.html
    mime_type: text/html

  - url: /(.*\.css)
    static_files: \1
    upload: .*\.css
    mime_type: text/css

  - url: /(.*\.js)
    static_files: \1
    upload: .*\.js
    mime_type: application/javascript

  - url: /(.*\.(gif|png|jpg|ico|svg))
    static_files: \1
    upload: .*\.(gif|png|jpg|ico|svg)
    mime_type: image/\2

  - url: /(.*)
    static_files: index.html
    upload: index.html
    mime_type: text/html

env_variables:
  API_KEY: "YOUR_OPENWEATHERMAP_API_KEY_HERE" 